-- liquibase formatted sql

-- changeset Robin.Mayer:1768770071-1
CREATE TABLE addresses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street       VARCHAR(255) NOT NULL,
    house_number VARCHAR(255) NOT NULL,
    postal_code  VARCHAR(255) NOT NULL,
    city         VARCHAR(255) NOT NULL
);

-- changeset Robin.Mayer:1768770071-2
CREATE INDEX idx_addresses_street ON addresses (street);
CREATE INDEX idx_addresses_house_number ON addresses (house_number);
CREATE INDEX idx_addresses_postal_code ON addresses (postal_code);
CREATE INDEX idx_addresses_city ON addresses (city);
